-- tabla .
CREATE TABLE CENTRO_OPERACION (
    ID NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(100),
    UBICACION VARCHAR2(100),
    RESPONSABLE VARCHAR2(100),
    ESTADO VARCHAR2(50)
);  
-- procedimiento almacenado .
CREATE OR REPLACE PROCEDURE SP_CENTRO_OPERACION_CRUD (
    P_OPCION        IN NUMBER,   -- 1=INSERT, 2=UPDATE, 3=DELETE, 4=SELECT
    P_ID            IN NUMBER,
    P_NOMBRE        IN VARCHAR2,
    P_UBICACION     IN VARCHAR2,
    P_RESPONSABLE   IN VARCHAR2,
    P_ESTADO        IN VARCHAR2,
    P_CURSOR        OUT SYS_REFCURSOR
) AS
BEGIN
    IF P_OPCION = 1 THEN
        INSERT INTO CENTRO_OPERACION
        VALUES (P_ID, P_NOMBRE, P_UBICACION, P_RESPONSABLE, P_ESTADO);

    ELSIF P_OPCION = 2 THEN
        UPDATE CENTRO_OPERACION
        SET NOMBRE = P_NOMBRE,
            UBICACION = P_UBICACION,
            RESPONSABLE = P_RESPONSABLE,
            ESTADO = P_ESTADO
        WHERE ID = P_ID;

    ELSIF P_OPCION = 3 THEN
        DELETE FROM CENTRO_OPERACION
        WHERE ID = P_ID;

    ELSIF P_OPCION = 4 THEN
        OPEN P_CURSOR FOR
        SELECT * FROM CENTRO_OPERACION;
    END IF;
END;
/

-- commit; - confirma transaccion en bd .
COMMIT;